# Generated by Django 5.2.13 on 2026-08-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0004_baseline_name_not_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='allow_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
