# Generated by Django 5.2.17 on 2026-09-05 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0008_rename_baseline_to_playbook'),
        ('tasks', '0018_rename_baseline_to_playbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playbookstep',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_steps', to='tasks.taskdefinition'),
        ),
    ]
