# Generated by Django 5.2.17 on 2026-09-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0010_remove_playbook_enabled_playbook_auto_enroll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
