# Generated by Django 5.2.17 on 2026-09-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0011_playbook_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='on_not_applicable',
            field=models.CharField(choices=[('skip', 'Skip'), ('stop', 'Stop')], default='stop', max_length=8),
        ),
    ]
