# Generated by Django 5.2.17 on 2026-09-28 13:58

from django.db import migrations, models


def fill_step_ids(apps, schema_editor):
    """Existing steps get ids s1, s2, … in their playbook's order."""
    PlaybookStep = apps.get_model("baselines", "PlaybookStep")
    Playbook = apps.get_model("baselines", "Playbook")
    for playbook in Playbook.objects.all():
        steps = PlaybookStep.objects.filter(playbook=playbook).order_by("order")
        for position, step in enumerate(steps, start=1):
            if not step.step_id:
                step.step_id = f"s{position}"
                step.save(update_fields=["step_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0012_playbookstep_on_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbook',
            name='flow',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playbookstep',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='playbookstep',
            name='step_id',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.RunPython(fill_step_ids, migrations.RunPython.noop),
    ]
