# Generated by Django 5.2.17 on 2026-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0013_playbook_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='on_failure',
            field=models.CharField(choices=[('stop', 'Stop'), ('continue', 'Continue')], default='stop', max_length=8),
        ),
    ]
