# Generated by Django 5.2.17 on 2026-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0014_playbookstep_on_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='color',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
