# Generated by Django 5.2.17 on 2026-09-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0015_playbookstep_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbookstep',
            name='outcome',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
