# Generated by Django 5.2.13 on 2026-07-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI-compatible (incl. Ollama, vLLM, LM Studio)'), ('anthropic', 'Anthropic')], default='openai', max_length=20)),
                ('base_url', models.URLField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('api_key_encrypted', models.BinaryField(blank=True, default=b'')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
