# Generated by Django 5.2.13 on 2026-08-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aisuggest', '0002_aiprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='kind',
            field=models.CharField(choices=[('openai', 'OpenAI-compatible (Ollama, vLLM, LM Studio, OpenAI)'), ('anthropic', 'Anthropic')], default='openai', max_length=20),
        ),
    ]
