# Generated by Django 6.0.4 on 2026-04-10 01:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('webhook', 'Webhook'), ('email', 'Email')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Webhook: {"url": "..."}, Email: {"recipients": ["..."]}')),
                ('on_firing', models.BooleanField(default=True)),
                ('on_resolved', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
