# Generated by Django 6.0.4 on 2026-04-10 01:17

from django.db import migrations


DEFAULT_RULES = [
    {
        "name": "High CPU Usage",
        "category": "cpu",
        "metric": "usage_percent",
        "operator": "gt",
        "threshold": 90.0,
        "severity": "critical",
        "duration_seconds": 300,
    },
    {
        "name": "Elevated CPU Usage",
        "category": "cpu",
        "metric": "usage_percent",
        "operator": "gt",
        "threshold": 75.0,
        "severity": "warning",
        "duration_seconds": 300,
    },
    {
        "name": "High Memory Usage",
        "category": "memory",
        "metric": "usage_percent",
        "operator": "gt",
        "threshold": 90.0,
        "severity": "critical",
        "duration_seconds": 120,
    },
    {
        "name": "Elevated Memory Usage",
        "category": "memory",
        "metric": "usage_percent",
        "operator": "gt",
        "threshold": 80.0,
        "severity": "warning",
        "duration_seconds": 120,
    },
    {
        "name": "Disk Nearly Full",
        "category": "disk",
        "metric": "usage_percent",
        "operator": "gt",
        "threshold": 90.0,
        "severity": "critical",
        "duration_seconds": 0,
    },
    {
        "name": "Disk Usage High",
        "category": "disk",
        "metric": "usage_percent",
        "operator": "gt",
        "threshold": 80.0,
        "severity": "warning",
        "duration_seconds": 0,
    },
    {
        "name": "High Swap Usage",
        "category": "memory",
        "metric": "swap_usage_percent",
        "operator": "gt",
        "threshold": 50.0,
        "severity": "warning",
        "duration_seconds": 300,
    },
]


def create_defaults(apps, schema_editor):
    AlertRule = apps.get_model("alerts", "AlertRule")
    for rule_data in DEFAULT_RULES:
        AlertRule.objects.get_or_create(
            name=rule_data["name"],
            defaults={**rule_data, "enabled": True, "is_default": True},
        )


def remove_defaults(apps, schema_editor):
    AlertRule = apps.get_model("alerts", "AlertRule")
    AlertRule.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_notificationchannel"),
    ]

    operations = [
        migrations.RunPython(create_defaults, remove_defaults),
    ]
