# Generated by Django 5.2.14 on 2026-05-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_more_default_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='fix_context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
