# Generated by Django 5.2.12 on 2026-07-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alert_fix_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
