# Generated by Django 5.2.17 on 2026-09-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_acknowledged_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='flap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
