# Generated by Django 5.2.17 on 2026-10-01 05:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hosts", "0022_log_tail_session"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagedStack",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=63)),
                ("compose_yaml", models.TextField()),
                ("env_encrypted", models.BinaryField(blank=True, default=b"")),
                ("revision", models.PositiveIntegerField(default=1)),
                ("working_dir", models.CharField(blank=True, max_length=500)),
                ("adopted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managed_stacks",
                        to="hosts.host",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="StackRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("compose_yaml", models.TextField()),
                ("env_encrypted", models.BinaryField(blank=True, default=b"")),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="stacks.managedstack",
                    ),
                ),
            ],
            options={
                "ordering": ("-number",),
            },
        ),
        migrations.AddConstraint(
            model_name="managedstack",
            constraint=models.UniqueConstraint(
                fields=("host", "name"), name="uniq_managed_stack"
            ),
        ),
        migrations.AddConstraint(
            model_name="stackrevision",
            constraint=models.UniqueConstraint(
                fields=("stack", "number"), name="uniq_stack_revision"
            ),
        ),
    ]
