# Generated by Django 5.2.17 on 2026-10-01 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0022_log_tail_session"),
        ("stacks", "0002_env_ticket"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="managedstack",
            name="adopt_report",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="managedstack",
            name="compose_file",
            field=models.CharField(default="compose.yaml", max_length=100),
        ),
        migrations.CreateModel(
            name="AdoptTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project", models.CharField(max_length=63)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="hosts.host",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
