# Generated by Django 5.2.17 on 2026-10-10 00:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0026_hash_agent_tokens'),
        ('stacks', '0004_registry_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='managedstack',
            name='git_branch',
            field=models.CharField(blank=True, default='main', max_length=200),
        ),
        migrations.AddField(
            model_name='managedstack',
            name='git_path',
            field=models.CharField(blank=True, default='compose.yaml', max_length=300),
        ),
        migrations.AddField(
            model_name='managedstack',
            name='git_pin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='managedstack',
            name='git_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='stackrevision',
            name='git_commit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='GitCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('token', 'HTTPS token'), ('ssh_key', 'SSH deploy key')], max_length=10)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('secret_encrypted', models.BinaryField()),
                ('known_hosts', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='managedstack',
            name='git_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stacks', to='stacks.gitcredential'),
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('commit', models.CharField(max_length=64)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='stacks.managedstack')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SourceTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hosts.host')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='stacks.sourcesnapshot')),
            ],
        ),
    ]
