# Generated by Django 5.2.17 on 2026-10-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0005_git_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitcredential',
            name='git_host',
            field=models.CharField(default='', max_length=255),
        ),
    ]
