# Generated by Django 5.2.13 on 2026-07-20 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('hosts', '0007_unmanageddevice'),
        ('tasks', '0010_seed_check_docker_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('enabled', models.BooleanField(default=True)),
                ('trigger', models.CharField(choices=[('event', 'When an event fires'), ('schedule', 'On a schedule')], max_length=12)),
                ('event', models.CharField(blank=True, default='', max_length=40)),
                ('min_severity', models.CharField(blank=True, default='', max_length=10)),
                ('event_tags', models.JSONField(blank=True, default=list)),
                ('cron_minute', models.CharField(blank=True, default='0', max_length=64)),
                ('cron_hour', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_dom', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_month', models.CharField(blank=True, default='*', max_length=64)),
                ('cron_dow', models.CharField(blank=True, default='*', max_length=64)),
                ('action_kind', models.CharField(choices=[('task', 'Task definition'), ('baseline', 'Baseline')], max_length=12)),
                ('baseline_name', models.CharField(blank=True, default='', max_length=120)),
                ('target', models.CharField(choices=[('event_host', 'The host from the event'), ('tags', 'Hosts matching tags'), ('host', 'A specific host'), ('all', 'All managed hosts')], default='event_host', max_length=12)),
                ('target_tags', models.JSONField(blank=True, default=list)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_celery_beat.periodictask')),
                ('target_host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hosts.host')),
                ('task_definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='tasks.taskdefinition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
