# Generated by Django 5.2.13 on 2026-07-21 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_acknowledged_until'),
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='event_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='alerts.alertrule'),
        ),
    ]
