# Generated by Django 5.2.13 on 2026-07-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automation_event_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='params_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
