# Generated by Django 5.2.13 on 2026-08-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0005_drop_baseline_name'),
        ('hosts', '0009_hostfirewall'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='event_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hosts.host'),
        ),
        migrations.AddField(
            model_name='automation',
            name='match_field',
            field=models.CharField(choices=[('any', 'Name or description'), ('rule', 'Name (alert rule)'), ('message', 'Description (alert text)')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='automation',
            name='match_mode',
            field=models.CharField(choices=[('contains', 'contains'), ('not_contains', 'does not contain')], default='contains', max_length=14),
        ),
        migrations.AddField(
            model_name='automation',
            name='match_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
