# Generated by Django 5.2.17 on 2026-08-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0006_automation_event_host_automation_match_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='dispatch_mode',
            field=models.CharField(choices=[('direct', 'All at once'), ('rollout', 'Wave by wave')], default='direct', max_length=8),
        ),
    ]
