# Generated by Django 5.2.17 on 2026-08-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0007_automation_dispatch_mode'),
        ('hosts', '0013_host_tag_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='event_tag_rows',
            field=models.ManyToManyField(blank=True, related_name='automations_by_event', to='hosts.tag'),
        ),
        migrations.AddField(
            model_name='automation',
            name='target_tag_rows',
            field=models.ManyToManyField(blank=True, related_name='automations_by_target', to='hosts.tag'),
        ),
    ]
