# Generated by Django 5.2.17 on 2026-08-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0008_automation_event_tag_rows_automation_target_tag_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='match_mode',
            field=models.CharField(choices=[('contains', 'contains'), ('not_contains', 'does not contain'), ('equals', 'is exactly'), ('not_equals', 'is not'), ('starts_with', 'starts with'), ('ends_with', 'ends with'), ('regex', 'matches regex'), ('not_regex', 'does not match regex')], default='contains', max_length=16),
        ),
    ]
