# Generated by Django 5.2.17 on 2026-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0009_alter_automation_match_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='community_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
