# Generated by Django 5.2.17 on 2026-09-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0011_rename_baseline_to_playbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='allow_high_risk',
            field=models.BooleanField(default=False),
        ),
    ]
