# Generated by Django 5.2.17 on 2026-09-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0013_rename_alert_fired_to_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='condition_logic',
            field=models.CharField(choices=[('all', 'Match all of these'), ('any', 'Match any of these')], default='all', max_length=3),
        ),
        migrations.AddField(
            model_name='automation',
            name='conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
