# Generated by Django 6.0.4 on 2026-04-15 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_multistep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='slug',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message="Slug must be lowercase with optional single '/' namespace separator.", regex='^[a-z0-9][a-z0-9_\\-]*(/[a-z0-9][a-z0-9_\\-]*)?$')]),
        ),
    ]
