# Generated by Django 5.2.13 on 2026-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_tasktemplate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='task',
            name='variables',
        ),
        migrations.AlterField(
            model_name='task',
            name='action',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='TaskStep',
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
    ]
