# Generated by Django 6.0.4 on 2026-04-15 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
        ('tasks', '0004_remove_tasktemplate_created_by_remove_task_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='step_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='step_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('pending', 'Pending'), ('dispatched', 'Dispatched'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('relevance', models.CharField(blank=True, max_length=255)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('standard', 'Standard'), ('high', 'High')], default='standard', max_length=10)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('community', 'Community')], default='private', max_length=12)),
                ('yaml_source', models.TextField()),
                ('parsed_spec', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forked_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='tasks.taskdefinition')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_definitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(blank=True, max_length=120)),
                ('host_count', models.IntegerField(default=0)),
                ('step_count', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], default='running', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasks.taskdefinition')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.taskrun'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['run', 'host', 'step_order'], name='tasks_task_run_id_f3a288_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state'], name='tasks_task_state_0a0b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdefinition',
            index=models.Index(fields=['owner', '-updated_at'], name='tasks_taskd_owner_i_8aed51_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdefinition',
            index=models.Index(fields=['visibility', '-updated_at'], name='tasks_taskd_visibil_495034_idx'),
        ),
    ]
