# Generated by Django 5.2.12 on 2026-06-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_policy_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('pending', 'Pending'), ('dispatched', 'Dispatched'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
