# Generated by Django 5.2.12 on 2026-06-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_add_skipped_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
