# Generated by Django 5.2.13 on 2026-07-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_automation_baseline_fk'),
        ('baselines', '0004_baseline_name_not_unique'),
        ('tasks', '0010_seed_check_docker_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='automations.automation'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='baselines.baseline'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual deploy'), ('automation', 'Automation'), ('baseline', 'Baseline')], default='manual', max_length=12),
        ),
    ]
