# Generated by Django 5.2.13 on 2026-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskrun_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual deploy'), ('automation', 'Automation'), ('baseline', 'Baseline'), ('reprovision', 'Reprovision')], default='manual', max_length=12),
        ),
    ]
