# Generated by Django 5.2.17 on 2026-08-26 23:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_taskrun_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchRing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('soak_hours', models.PositiveIntegerField(default=24)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('order',), name='uniq_patch_ring_order')],
            },
        ),
        migrations.AddField(
            model_name='taskrun',
            name='ring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasks.patchring'),
        ),
        migrations.CreateModel(
            name='PatchRollout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('soaking', 'Soaking'), ('halted', 'Halted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('failure_threshold_pct', models.PositiveIntegerField(default=10)),
                ('min_results_before_halt', models.PositiveIntegerField(default=3)),
                ('halted_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ring_started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollouts_created', to=settings.AUTH_USER_MODEL)),
                ('current_ring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollouts', to='tasks.patchring')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollouts', to='tasks.taskdefinition')),
                ('halted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollouts_halted', to=settings.AUTH_USER_MODEL)),
                ('resumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rollouts_resumed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskrun',
            name='rollout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasks.patchrollout'),
        ),
    ]
