"""Rename patch rings to waves, and soak windows to validation windows.

Written by hand rather than autogenerated. Django's autodetector produced a
DeleteModel + CreateModel pair, which would have dropped every configured wave
and every rollout's history. These are renames, so they are expressed as
renames and the rows survive.
"""

from django.db import migrations, models


def soaking_to_validating(apps, schema_editor):
    apps.get_model("tasks", "PatchRollout").objects.filter(
        state="soaking"
    ).update(state="validating")


def validating_to_soaking(apps, schema_editor):
    apps.get_model("tasks", "PatchRollout").objects.filter(
        state="validating"
    ).update(state="soaking")


class Migration(migrations.Migration):

    dependencies = [("tasks", "0013_patchring_taskrun_ring_patchrollout_taskrun_rollout")]

    operations = [
        # The constraint is dropped before the rename and re-added after, because
        # its name embeds the old noun.
        migrations.RemoveConstraint(
            model_name="patchring", name="uniq_patch_ring_order",
        ),
        migrations.RenameModel(old_name="PatchRing", new_name="PatchWave"),
        migrations.RenameField(
            model_name="patchwave", old_name="soak_hours", new_name="validation_hours",
        ),
        migrations.RenameField(
            model_name="patchrollout", old_name="current_ring", new_name="current_wave",
        ),
        migrations.RenameField(
            model_name="patchrollout", old_name="ring_started_at",
            new_name="wave_started_at",
        ),
        migrations.RenameField(
            model_name="taskrun", old_name="ring", new_name="wave",
        ),
        migrations.AddConstraint(
            model_name="patchwave",
            constraint=models.UniqueConstraint(
                fields=("order",), name="uniq_patch_wave_order"
            ),
        ),
        migrations.AlterField(
            model_name="patchrollout",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"), ("running", "Running"),
                    ("validating", "Validating"), ("halted", "Halted"),
                    ("completed", "Completed"), ("cancelled", "Cancelled"),
                ],
                default="pending", max_length=12,
            ),
        ),
        migrations.RunPython(soaking_to_validating, validating_to_soaking),
    ]
