# Generated by Django 5.2.17 on 2026-08-27 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0005_baseline_allow_high_risk'),
        ('tasks', '0014_ring_to_wave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patchrollout',
            name='action_kind',
            field=models.CharField(choices=[('task', 'Task definition'), ('baseline', 'Baseline')], default='task', max_length=12),
        ),
        migrations.AddField(
            model_name='patchrollout',
            name='baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollouts', to='baselines.baseline'),
        ),
        migrations.AlterField(
            model_name='patchrollout',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollouts', to='tasks.taskdefinition'),
        ),
        migrations.AddConstraint(
            model_name='patchrollout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('baseline__isnull', True), ('definition__isnull', False)), models.Q(('baseline__isnull', False), ('definition__isnull', True)), _connector='OR'), name='rollout_has_exactly_one_target'),
        ),
    ]
