# Generated by Django 5.2.17 on 2026-08-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0013_host_tag_rows'),
        ('tasks', '0015_patchrollout_action_kind_patchrollout_baseline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchwave',
            name='tag_rows',
            field=models.ManyToManyField(blank=True, related_name='waves', to='hosts.tag'),
        ),
    ]
