# Generated by Django 5.2.17 on 2026-09-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_rename_baseline_to_playbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdefinition',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
