# Generated by Django 5.2.17 on 2026-09-26 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_transportack'),
        ('tasks', '0024_task_result_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=60)),
                ('action', models.CharField(max_length=64)),
                ('evidence_type', models.CharField(max_length=40)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_matches', to='hosts.host')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunt_matches', to='tasks.taskrun')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_matches', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['run', 'host'], name='tasks_huntm_run_id_f1fed3_idx')],
            },
        ),
    ]
