# Generated by Django 5.2.17 on 2026-09-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_huntmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
