# Generated by Django 5.2.17 on 2026-09-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_seed_hunt_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('blocked', 'Blocked'), ('pending', 'Pending'), ('dispatched', 'Dispatched'), ('executing', 'Executing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('skipped', 'Skipped'), ('not_applicable', 'Not applicable')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='state',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial'), ('not_applicable', 'Not applicable')], default='running', max_length=16),
        ),
    ]
