# Generated by Django 5.2.17 on 2026-09-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_relevance_into_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='on_not_applicable',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
