# Generated by Django 5.2.17 on 2026-09-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_task_on_not_applicable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='branch',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='task',
            name='guard',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='step_ref',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
