# Generated by Django 5.2.17 on 2026-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_task_playbook_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='on_failure',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
