# Generated by Django 5.2.17 on 2026-09-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_task_on_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='flow_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
