# Generated by Django 5.2.17 on 2026-10-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0033_taskrun_flow_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="patchrollout",
            name="host_ids",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskrun",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual deploy"),
                    ("automation", "Automation"),
                    ("playbook", "Playbook"),
                    ("reprovision", "Reprovision"),
                    ("policy", "Policy"),
                ],
                default="manual",
                max_length=12,
            ),
        ),
    ]
