# Generated by Django 5.2.17 on 2026-10-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0034_patchrollout_host_ids_alter_taskrun_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdefinition",
            name="content_source",
            field=models.CharField(
                choices=[
                    ("organization", "Organization"),
                    ("community", "Community"),
                    ("vendor", "Vendor"),
                ],
                default="organization",
                max_length=12,
            ),
        ),
    ]
