# Generated by Django 5.2.17 on 2026-10-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_seed_container_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchrollout',
            name='batch',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
