# Generated by Django 5.2.17 on 2026-09-29 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0018_host_agent_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(blank=True, max_length=64)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('item_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=dict)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='software_snapshot', to='hosts.host')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dpkg', 'dpkg'), ('rpm', 'rpm'), ('apk', 'apk'), ('pacman', 'pacman'), ('flatpak', 'flatpak'), ('snap', 'snap'), ('winget', 'winget'), ('chocolatey', 'chocolatey'), ('scoop', 'scoop'), ('registry', 'registry'), ('windows_update', 'Windows Update'), ('brew', 'brew')], max_length=20)),
                ('package_id', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('name_key', models.CharField(db_index=True, max_length=300)),
                ('version', models.CharField(blank=True, max_length=120)),
                ('latest_version', models.CharField(blank=True, max_length=120)),
                ('scope', models.CharField(choices=[('machine', 'Machine'), ('user', 'User')], default='machine', max_length=10)),
                ('user', models.CharField(blank=True, max_length=120)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('managed', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software', to='hosts.host')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'name_key'], name='software_so_host_id_cb46a1_idx')],
                'constraints': [models.UniqueConstraint(fields=('host', 'source', 'package_id', 'scope', 'user'), name='uniq_software_item')],
            },
        ),
    ]
