# Generated by Django 5.2.17 on 2026-10-01 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0019_host_agent_allowlist"),
        ("software", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwareitem",
            name="outdated_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PendingUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("windows", "Windows Update"),
                            ("linux", "Linux package"),
                        ],
                        max_length=10,
                    ),
                ),
                ("key", models.CharField(max_length=300)),
                ("title", models.CharField(blank=True, max_length=300)),
                ("severity", models.CharField(blank=True, max_length=20)),
                ("classification", models.CharField(blank=True, max_length=60)),
                ("reboot_required", models.BooleanField(default=False)),
                ("version", models.CharField(blank=True, max_length=120)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_updates",
                        to="hosts.host",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "key"], name="software_pe_kind_3e5e58_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "kind", "key"), name="uniq_pending_update"
                    )
                ],
            },
        ),
    ]
