# Generated by Django 5.2.17 on 2026-10-01 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("software", "0002_softwareitem_outdated_since_pendingupdate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("windows", "Windows Update"),
                            ("linux", "Linux package"),
                        ],
                        max_length=10,
                    ),
                ),
                ("key", models.CharField(max_length=300)),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("declined", "Declined")],
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key"), name="uniq_update_decision"
                    )
                ],
            },
        ),
    ]
