# Generated by Django 5.2.14 on 2026-05-15 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_host_agent_version'),
        ('vulns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('requested', 'Requested'), ('launched', 'Launched'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted')], default='requested', max_length=16)),
                ('nessus_scan_id', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(default='', max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_via_task', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_scans', to='hosts.host')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuln_scans_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['host', '-requested_at'], name='vulns_vulns_host_id_66f348_idx'), models.Index(fields=['state'], name='vulns_vulns_state_92ac8f_idx')],
            },
        ),
    ]
