# Generated by Django 5.2.12 on 2026-06-03 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_summary_scores(apps, schema_editor):
    """Compute score + debt for every existing VulnSummary row.

    New summaries default to score=100; that's wrong for hosts that
    already have findings before this migration ran. Walk each row and
    recompute against the live severity counts so existing fleets get an
    accurate score the first time they load the dashboard after upgrade.

    Uses the same weights as apps.vulns.scoring.compute_score —
    duplicated here because RunPython operates on historical model
    classes that don't include arbitrary attached methods. Keep these
    formulas in lockstep with scoring.py.
    """
    VulnSummary = apps.get_model("vulns", "VulnSummary")
    for s in VulnSummary.objects.all():
        debt = int(round(
            10 * s.critical + 3 * s.high + 1 * s.medium + 0.2 * s.low
        ))
        s.debt = debt
        s.score = max(0, 100 - debt)
        s.save(update_fields=["score", "debt"])


def reset_summary_scores(apps, schema_editor):
    VulnSummary = apps.get_model("vulns", "VulnSummary")
    VulnSummary.objects.update(score=100, debt=0)


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_host_agent_version'),
        ('vulns', '0003_scanner_field_and_external_scan_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnsummary',
            options={'ordering': ['-debt', '-critical', '-high'], 'verbose_name': 'Vulnerability Summary', 'verbose_name_plural': 'Vulnerability Summaries'},
        ),
        migrations.AddField(
            model_name='vulnsummary',
            name='debt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vulnsummary',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.RunPython(backfill_summary_scores, reverse_code=reset_summary_scores),
        migrations.CreateModel(
            name='VulnFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanner', models.CharField(choices=[('nessus', 'Nessus'), ('greenbone', 'Greenbone / OpenVAS'), ('trivy', 'Trivy')], max_length=16)),
                ('plugin_id_or_oid', models.CharField(max_length=128)),
                ('cve_id', models.CharField(blank=True, default='', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Informational')], max_length=16)),
                ('state', models.CharField(choices=[('open', 'Open'), ('fixed', 'Fixed'), ('suppressed', 'Suppressed')], default='open', max_length=16)),
                ('package_name', models.CharField(blank=True, default='', max_length=255)),
                ('installed_version', models.CharField(blank=True, default='', max_length=80)),
                ('fixed_version', models.CharField(blank=True, default='', max_length=80)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_findings', to='hosts.host')),
            ],
            options={
                'ordering': ['-severity', '-last_seen'],
                'indexes': [models.Index(fields=['host', 'state', 'severity'], name='vulns_vulnf_host_id_e01eb2_idx'), models.Index(fields=['scanner', 'state'], name='vulns_vulnf_scanner_83624b_idx'), models.Index(fields=['cve_id'], name='vulns_vulnf_cve_id_2d79d3_idx')],
                'constraints': [models.UniqueConstraint(fields=('host', 'scanner', 'plugin_id_or_oid'), name='vuln_finding_unique_per_host_scanner_plugin')],
            },
        ),
        migrations.CreateModel(
            name='VulnScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('debt', models.IntegerField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuln_score_history', to='hosts.host')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['host', '-date'], name='vulns_vulns_host_id_d8a805_idx')],
                'constraints': [models.UniqueConstraint(fields=('host', 'date'), name='vuln_score_history_unique_per_host_per_day')],
            },
        ),
    ]
