# Generated by Django 5.2.12 on 2026-06-05 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0004_findings_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnsummary',
            options={'ordering': ['score', '-critical', '-high'], 'verbose_name': 'Vulnerability Summary', 'verbose_name_plural': 'Vulnerability Summaries'},
        ),
        migrations.RemoveField(
            model_name='vulnscorehistory',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='vulnsummary',
            name='debt',
        ),
    ]
