# Generated by Django 5.2.12 on 2026-06-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0005_drop_debt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vulnfinding',
            options={'ordering': ['-last_seen']},
        ),
        migrations.AddField(
            model_name='vulnscan',
            name='ingested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
