# Generated by Django 5.2.17 on 2026-08-26 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0006_alter_vulnfinding_options_vulnscan_ingested_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KevEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('date_added', models.DateField()),
                ('cisa_due_date', models.DateField(blank=True, null=True)),
                ('ransomware', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('bundled', 'Bundled snapshot'), ('live', 'Fetched from CISA')], default='bundled', max_length=8)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'KEV entries',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='RemediationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kev_days', models.PositiveIntegerField(default=14)),
                ('critical_days', models.PositiveIntegerField(default=15)),
                ('high_days', models.PositiveIntegerField(default=30)),
                ('medium_days', models.PositiveIntegerField(default=90)),
                ('low_days', models.PositiveIntegerField(default=180)),
                ('use_cisa_due_date', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'remediation policies',
            },
        ),
        migrations.AddField(
            model_name='vulnfinding',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='VulnException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('accepted', 'Accepted risk'), ('deferred', 'Deferred')], default='accepted', max_length=10)),
                ('reason', models.TextField()),
                ('expires_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vuln_exceptions', to=settings.AUTH_USER_MODEL)),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exception', to='vulns.vulnfinding')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
