# Generated by Django 5.2.17 on 2026-08-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulns', '0008_load_kev_and_backfill_due_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnsummary',
            name='due_soon_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vulnsummary',
            name='overdue_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
