# Generated by Django 5.2.17 on 2026-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulns", "0011_rescore_for_overdue_weighted_curve"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnfinding",
            name="advisory",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="affected_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="cvss_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="cvss_vector",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="primary_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="references",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="vulnfinding",
            name="vendor_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
