# Generated by Django 5.2.17 on 2026-10-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulns", "0012_vulnfinding_advisory_vulnfinding_affected_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vulnfinding",
            name="scanner",
            field=models.CharField(
                choices=[
                    ("nessus", "Nessus"),
                    ("greenbone", "Greenbone / OpenVAS"),
                    ("trivy", "Trivy"),
                    ("vigil", "Vigil"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vulnscan",
            name="scanner",
            field=models.CharField(
                choices=[
                    ("nessus", "Nessus"),
                    ("greenbone", "Greenbone / OpenVAS"),
                    ("trivy", "Trivy"),
                    ("vigil", "Vigil"),
                ],
                default="nessus",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="FindingEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("package", "Installed package"),
                            ("registry", "Registry entry"),
                            ("file", "File on disk"),
                            ("process", "Running process"),
                            ("port", "Listening port"),
                            ("missing_update", "Missing security update"),
                            ("outdated_app", "Outdated app"),
                            ("scanner", "Scanner report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(max_length=300)),
                ("summary", models.CharField(blank=True, default="", max_length=300)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("observed_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="vulns.vulnfinding",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("finding", "kind", "key"), name="uniq_finding_evidence"
                    )
                ],
            },
        ),
    ]
