# Generated by Django 5.2.17 on 2026-10-01 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulns", "0013_alter_vulnfinding_scanner_alter_vulnscan_scanner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpssScore",
            fields=[
                (
                    "cve_id",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("epss", models.FloatField()),
                ("percentile", models.FloatField()),
                ("score_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OsvAdvisory",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("modified", models.DateTimeField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, default="", max_length=500)),
                ("details", models.TextField(blank=True, default="")),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("severity", models.CharField(blank=True, default="", max_length=16)),
                ("cvss_score", models.FloatField(blank=True, null=True)),
                (
                    "cvss_vector",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("references", models.JSONField(blank=True, default=list)),
                ("withdrawn", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="OsvAffected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ecosystem", models.CharField(max_length=80)),
                ("package", models.CharField(max_length=200)),
                ("ranges", models.JSONField(blank=True, default=list)),
                ("versions", models.JSONField(blank=True, default=list)),
                ("fixed", models.CharField(blank=True, default="", max_length=120)),
                (
                    "advisory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affected",
                        to="vulns.osvadvisory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["ecosystem", "package"],
                        name="vulns_osvaf_ecosyst_0693eb_idx",
                    )
                ],
            },
        ),
    ]
