# Generated by Django 5.2.17 on 2026-10-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulns", "0014_epssscore_osvadvisory_osvaffected"),
    ]

    operations = [
        migrations.AddField(
            model_name="vulnfinding",
            name="fix_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=300
            ),
        ),
    ]
