# Generated by Django 5.2.17 on 2026-10-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulns", "0016_fix_groups_rescore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vulnfinding",
            name="scanner",
            field=models.CharField(
                choices=[
                    ("nessus", "Nessus"),
                    ("greenbone", "Greenbone / OpenVAS"),
                    ("trivy", "Trivy"),
                    ("vigil", "Vigil"),
                    ("detection", "Detection task"),
                    ("anvil", "Anvil"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vulnscan",
            name="scanner",
            field=models.CharField(
                choices=[
                    ("nessus", "Nessus"),
                    ("greenbone", "Greenbone / OpenVAS"),
                    ("trivy", "Trivy"),
                    ("vigil", "Vigil"),
                    ("detection", "Detection task"),
                    ("anvil", "Anvil"),
                ],
                default="nessus",
                max_length=16,
            ),
        ),
    ]
