# Generated by Django 5.2.12 on 2026-04-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('metric', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_points', to='hosts.host')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'category', 'metric', 'time'], name='metrics_met_host_id_2f24de_idx')],
            },
        ),
    ]
