# Generated by Django 5.2.13 on 2026-07-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, default='', max_length=60)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('accent', models.CharField(blank=True, default='', max_length=7)),
                ('footer_text', models.CharField(blank=True, default='', max_length=200)),
                ('support_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
