# Generated by Django 5.2.14 on 2026-05-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_dist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbinary',
            name='platform',
            field=models.CharField(choices=[('linux-amd64', 'Linux (x86-64)'), ('linux-arm64', 'Linux (ARM64)'), ('windows-amd64', 'Windows (x86-64)'), ('darwin-amd64', 'macOS (Intel)'), ('darwin-arm64', 'macOS (Apple Silicon)')], max_length=30, unique=True),
        ),
    ]
