# Generated by Django 5.2.13 on 2026-08-01 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baselines', '0004_baseline_name_not_unique'),
        ('hosts', '0008_host_maintenance_until'),
        ('tasks', '0012_alter_taskrun_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OSImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('os_family', models.CharField(choices=[('ubuntu', 'Ubuntu'), ('debian', 'Debian'), ('rhel', 'RHEL family')], max_length=16)),
                ('version', models.CharField(max_length=40)),
                ('architecture', models.CharField(default='x86_64', max_length=32)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('importing', 'Importing'), ('ready', 'Ready'), ('failed', 'Failed')], default='importing', max_length=12)),
                ('import_error', models.TextField(blank=True)),
                ('kernel_path', models.CharField(blank=True, max_length=512)),
                ('initrd_path', models.CharField(blank=True, max_length=512)),
                ('tree_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='os_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['os_family', '-version'],
            },
        ),
        migrations.CreateModel(
            name='InstallProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('disk_target', models.CharField(max_length=120)),
                ('partition_scheme', models.CharField(default='lvm', max_length=40)),
                ('filesystem', models.CharField(default='ext4', max_length=20)),
                ('network_mode', models.CharField(choices=[('dhcp', 'DHCP'), ('static', 'Static')], default='dhcp', max_length=10)),
                ('static_address', models.CharField(blank=True, max_length=64)),
                ('gateway', models.CharField(blank=True, max_length=64)),
                ('dns', models.CharField(blank=True, max_length=160)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('locale', models.CharField(default='en_US.UTF-8', max_length=32)),
                ('keyboard', models.CharField(default='us', max_length=32)),
                ('admin_username', models.CharField(max_length=64)),
                ('admin_password_encrypted', models.BinaryField(blank=True, default=b'')),
                ('ssh_authorized_keys', models.TextField(blank=True)),
                ('extra_packages', models.JSONField(blank=True, default=list)),
                ('raw_append', models.TextField(blank=True)),
                ('deadline_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='install_profiles', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='reprovision.osimage')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RebuildJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('staging', 'Staging'), ('staged', 'Staged'), ('rebooting', 'Rebooting'), ('installing', 'Installing'), ('enrolling', 'Enrolling'), ('completed', 'Completed'), ('failed', 'Failed'), ('aborted', 'Aborted'), ('timed_out', 'Timed out')], default='pending', max_length=12)),
                ('state_changed_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('failure_reason', models.TextField(blank=True)),
                ('answer_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('answer_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('answer_fetch_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('enroll_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('enroll_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('preflight', models.JSONField(blank=True, default=dict)),
                ('completion_tag', models.CharField(blank=True, max_length=120)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rebuild_jobs', to='hosts.host')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='reprovision.osimage')),
                ('post_baseline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuild_jobs', to='baselines.baseline')),
                ('post_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuild_jobs', to='tasks.taskrun')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='reprovision.installprofile')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuild_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
