# Generated by Django 5.2.13 on 2026-08-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprovision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='osimage',
            name='bytes_downloaded',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='osimage',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='osimage',
            name='status',
            field=models.CharField(choices=[('downloading', 'Downloading'), ('importing', 'Importing'), ('ready', 'Ready'), ('failed', 'Failed')], default='importing', max_length=12),
        ),
    ]
