# Generated by Django 5.2.13 on 2026-08-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reprovision', '0002_osimage_bytes_downloaded_osimage_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installprofile',
            name='completion_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
