# Generated by Django 5.2.17 on 2026-08-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0013_host_tag_rows'),
        ('reprovision', '0003_installprofile_completion_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='installprofile',
            name='completion_tag_rows',
            field=models.ManyToManyField(blank=True, related_name='install_profiles', to='hosts.tag'),
        ),
        migrations.AddField(
            model_name='rebuildjob',
            name='completion_tag_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuild_jobs', to='hosts.tag'),
        ),
    ]
