"""The wiki's action reference must describe actions that actually exist.

It had drifted into fiction: `get_status`, `ping`, `run_script` and
`shutdown` were all documented and none of them are real, and
`restart_service` was given a `service` param when it takes `service_name`.
A definition written from that page fails validation the moment it is saved,
which is the worst place to learn the reference was wrong.

The reference is now generated by ``manage.py render_wiki_actions`` from
ACTION_REGISTRY. These tests check three things:

1. The page still matches the registry, action for action and param for param.
2. Regenerating it would change nothing, so nobody has hand-edited the block.
3. Every task definition shown anywhere on the page actually parses. The page
   promises the reader a definition they can copy and save; this is what makes
   that promise true.
"""

import html
import re
from pathlib import Path

from django.conf import settings
from django.core.management import call_command
from django.core.management.base import CommandError
from django.test import TestCase

from .management.commands.render_wiki_actions import BEGIN, END, example_yaml
from .spec import ACTION_REGISTRY, SpecError, parse_and_validate


def _wiki() -> str:
    path = Path(settings.BASE_DIR).parent / "wiki" / "vigil-wiki.html"
    if not path.is_file():
        return ""
    return path.read_text(encoding="utf-8")


def _generated(text: str) -> str:
    """Only the generated action reference, not the prose around it."""
    return text[text.index(BEGIN):text.index(END)]


def _actions(block: str) -> dict[str, str]:
    """Map action name -> the HTML of its disclosure."""
    found = {}
    for chunk in block.split("<details class=\"action\"")[1:]:
        name = re.search(r'<code class="action-name">(\w+)</code>', chunk)
        if name:
            found[name.group(1)] = chunk[:chunk.index("</details>")]
    return found


def _plain_yaml(pre_html: str) -> str:
    """The text of a <pre> block, with highlight spans and entities removed."""
    text = re.sub(r"<[^>]+>", "", pre_html)
    return html.unescape(text)


def _task_yaml_blocks(text: str) -> list[str]:
    """Every <pre> on the page that is a task definition.

    Detected by shape rather than by position: a task definition is the only
    thing on this page with a top-level ``name:`` and ``actions:``. Config
    files, compose files and shell transcripts are left alone.
    """
    blocks = []
    for pre in re.findall(r"<pre>(.*?)</pre>", text, re.S):
        body = _plain_yaml(pre)
        if re.search(r"^name:", body, re.M) and re.search(r"^actions:", body, re.M):
            blocks.append(body)
    return blocks


class WikiActionReferenceTests(TestCase):
    """The generated block and ACTION_REGISTRY say the same thing."""

    def setUp(self):
        self.text = _wiki()
        if not self.text:
            self.skipTest("wiki not present in this build")
        self.block = _generated(self.text)
        self.actions = _actions(self.block)

    def test_it_lists_exactly_the_registered_actions(self):
        self.assertEqual(
            sorted(self.actions), sorted(ACTION_REGISTRY),
            "the wiki's action reference no longer matches ACTION_REGISTRY. "
            "Run: manage.py render_wiki_actions")

    def test_no_invented_action_comes_back(self):
        """Named individually: these four were documented for months."""
        for ghost in ("get_status", "ping", "run_script", "shutdown"):
            self.assertNotIn(
                ghost, self.actions,
                f"{ghost!r} is documented but does not exist")

    def test_each_action_shows_the_risk_the_registry_assigns(self):
        for name, chunk in self.actions.items():
            shown = re.search(r'data-risk="(\w+)"', chunk)
            self.assertIsNotNone(shown, f"{name}: no risk tier rendered")
            self.assertEqual(
                shown.group(1), ACTION_REGISTRY[name]["risk"],
                f"{name}: wiki says risk={shown.group(1)}, registry says "
                f"{ACTION_REGISTRY[name]['risk']}")

    def test_required_and_optional_params_match_the_registry(self):
        """The subtle half of the original defect: a real action with a param
        name that was never right."""
        for name, chunk in self.actions.items():
            rows = re.findall(
                r"<tr><td><code>([\w.]+)</code></td><td>"
                r'<span class="param-(req|opt)">', chunk)
            required = [p for p, kind in rows if kind == "req"]
            optional = [p for p, kind in rows if kind == "opt"]
            entry = ACTION_REGISTRY[name]
            self.assertEqual(
                required, list(entry["required"]),
                f"{name}: wiki required={required}, registry "
                f"{list(entry['required'])}")
            self.assertEqual(
                optional, list(entry["optional"]),
                f"{name}: wiki optional={optional}, registry "
                f"{list(entry['optional'])}")

    def test_every_action_carries_a_copyable_example(self):
        for name, chunk in self.actions.items():
            self.assertIn("<pre>", chunk, f"{name}: no example YAML")
            self.assertIn("copy-btn", chunk, f"{name}: no copy button")

    def test_the_page_is_what_the_generator_would_write(self):
        """Nobody has hand-edited the generated block.

        Hand-edits are how the reference drifted the first time, and an edit
        inside the markers is silently discarded by the next regeneration.
        """
        try:
            call_command("render_wiki_actions", "--check")
        except CommandError as exc:
            self.fail(f"{exc}")


class WikiExampleYamlTests(TestCase):
    """Every definition printed on the page is one a reader could save."""

    def setUp(self):
        self.text = _wiki()
        if not self.text:
            self.skipTest("wiki not present in this build")

    def test_every_generated_example_validates(self):
        for name in ACTION_REGISTRY:
            with self.subTest(action=name):
                try:
                    parse_and_validate(example_yaml(name))
                except SpecError as exc:
                    self.fail(f"{name}: its own example does not validate: {exc}")

    def test_every_generated_example_uses_the_action_it_documents(self):
        for name in ACTION_REGISTRY:
            with self.subTest(action=name):
                parsed = parse_and_validate(example_yaml(name))
                types = [a["type"] for a in parsed["actions"]]
                self.assertIn(
                    name, types,
                    f"{name}: its example does not actually use it")

    def test_every_task_definition_on_the_page_validates(self):
        """Including the hand-written ones outside the generated block.

        The page tells the reader these can be copied and saved as-is. An
        example that fails validation makes that a lie, and a reader who hits
        it has no way to tell whether they mistyped or the doc is wrong.
        """
        blocks = _task_yaml_blocks(self.text)
        self.assertGreater(
            len(blocks), len(ACTION_REGISTRY),
            "found fewer task definitions than there are actions — has the "
            "markup changed?")
        for body in blocks:
            with self.subTest(first_line=body.strip().split("\n")[0]):
                try:
                    parse_and_validate(body)
                except SpecError as exc:
                    self.fail(f"a YAML example on the page is invalid: {exc}"
                              f"\n\n{body}")


class WikiVersionTests(TestCase):
    def setUp(self):
        self.text = _wiki()
        if not self.text:
            self.skipTest("wiki not present in this build")

    def test_the_sidebar_version_badge_matches_this_build(self):
        badge = re.search(r'sidebar-version">v([\d.]+)', self.text)
        self.assertIsNotNone(badge, "version badge missing from the wiki")
        self.assertEqual(badge.group(1), settings.VIGIL_VERSION)

    def test_the_page_footer_matches_this_build(self):
        """The footer said v2026.3.0 for nine releases."""
        footer = re.search(r"Vigil v([\d.]+) &middot; Released under", self.text)
        self.assertIsNotNone(footer, "version line missing from the page footer")
        self.assertEqual(
            footer.group(1), settings.VIGIL_VERSION,
            "the wiki's footer version is stale")
