# Generated by Django 5.2.13 on 2026-07-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilsso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, default='')),
                ('app_slug', models.SlugField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
