# Generated by Django 5.2.13 on 2026-07-29 22:22

from django.db import migrations, models


def create_global_site(apps, schema_editor):
    Site = apps.get_model("business_sites", "Site")
    Site.objects.get_or_create(
        slug="global",
        defaults={
            "name": "Global",
            "description": "Policies here apply in every site unless suppressed.",
            "is_global": True,
            "is_default": False,
        },
    )


def remove_global_site(apps, schema_editor):
    Site = apps.get_model("business_sites", "Site")
    Site.objects.filter(is_global=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('business_sites', '0002_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_global_site, remove_global_site),
    ]
