# Generated by Django 5.2.13 on 2026-07-29 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alert_acknowledged_until'),
        ('automations', '0004_automation_baseline_fk'),
        ('baselines', '0004_baseline_name_not_unique'),
        ('business_sites', '0003_global_site'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('automation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignment', to='automations.automation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_assignments', to='business_sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='BaselineSiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('baseline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignment', to='baselines.baseline')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_assignments', to='business_sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelSiteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignment', to='alerts.notificationchannel')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_assignments', to='business_sites.site')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='business_sites.site')),
            ],
            options={
                'unique_together': {('site', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSiteRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='business_sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'site')},
            },
        ),
    ]
