# Generated by Django 5.2.13 on 2026-07-30 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_sites', '0005_unify_global_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=20)),
                ('verb', models.CharField(max_length=20)),
                ('user_site_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='business_sites.usersiterole')),
            ],
            options={
                'unique_together': {('user_site_role', 'app', 'verb')},
            },
        ),
    ]
