# Generated by Django 5.2.17 on 2026-09-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0009_alter_playbook_created_by_and_more'),
        ('business_sites', '0008_rename_baseline_site_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbooksiteassignment',
            name='playbook',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_assignment', to='baselines.playbook'),
        ),
        migrations.AlterField(
            model_name='playbooksiteassignment',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_assignments', to='business_sites.site'),
        ),
    ]
