# Generated by Django 5.2.13 on 2026-07-18 03:08

import apps.statuspage.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.statuspage.models._token, max_length=64, unique=True)),
                ('title', models.CharField(default='Service status', max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('host_ids', models.JSONField(blank=True, default=list)),
                ('site_id', models.UUIDField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('hide_badge', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
