# Generated by Django 5.2.13 on 2026-07-23 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_unmanageddevice'),
        ('statuspage', '0002_statuspage_host_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostUptimeSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(db_index=True)),
                ('up', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uptime_samples', to='hosts.host')),
            ],
            options={
                'indexes': [models.Index(fields=['host', 'time'], name='statuspage__host_id_10dc4d_idx')],
            },
        ),
    ]
