# Generated by Django 5.2.17 on 2026-10-01 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdatePolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("target_tags", models.JSONField(blank=True, default=list)),
                ("site_id", models.UUIDField(blank=True, null=True)),
                ("cron_minute", models.CharField(default="0", max_length=64)),
                ("cron_hour", models.CharField(default="2", max_length=64)),
                ("cron_dow", models.CharField(default="*", max_length=64)),
                ("window_hours", models.PositiveSmallIntegerField(default=4)),
                (
                    "wave_group_tag",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "approval_mode",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("approve", "Approve each change"),
                        ],
                        default="automatic",
                        max_length=10,
                    ),
                ),
                ("patch_enabled", models.BooleanField(default=False)),
                ("windows_classifications", models.JSONField(blank=True, default=list)),
                ("deferral_days", models.PositiveSmallIntegerField(default=7)),
                (
                    "reboot",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("in_window", "In the window"),
                            ("ask", "Ask the user"),
                        ],
                        default="in_window",
                        max_length=10,
                    ),
                ),
                (
                    "linux_updates",
                    models.CharField(
                        choices=[
                            ("security", "Security updates only"),
                            ("all", "All updates"),
                        ],
                        default="security",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AppRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app", models.CharField(max_length=200)),
                ("source", models.CharField(blank=True, default="", max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("latest", "Latest"),
                            ("pinned", "Pinned"),
                            ("absent", "Absent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=80)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_rules",
                        to="policies.updatepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "app", "source"), name="uniq_policy_app_rule"
                    )
                ],
            },
        ),
    ]
