# Generated by Django 5.2.17 on 2026-10-01 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
        ("tasks", "0034_patchrollout_host_ids_alter_taskrun_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="updatepolicy",
            name="task_definition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="tasks.taskdefinition",
            ),
        ),
    ]
