# Generated by Django 5.2.17 on 2026-10-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0003_policychange"),
    ]

    operations = [
        migrations.AddField(
            model_name="updatepolicy",
            name="allow_high_risk",
            field=models.BooleanField(default=False),
        ),
    ]
