# Generated by Django 5.2.12 on 2026-04-02 22:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('kernel', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agent_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Enrollment'), ('online', 'Online'), ('offline', 'Offline'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('mode', models.CharField(choices=[('monitor', 'Monitor'), ('managed', 'Managed'), ('full_control', 'Full Control')], default='monitor', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('last_checkin', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
