# Generated by Django 5.2.12 on 2026-07-14 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_host_agent_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(blank=True, max_length=120)),
                ('stack', models.CharField(blank=True, max_length=200)),
                ('service', models.CharField(blank=True, max_length=200)),
                ('cpu_percent', models.FloatField(blank=True, null=True)),
                ('mem_usage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mem_limit_bytes', models.BigIntegerField(blank=True, null=True)),
                ('mem_percent', models.FloatField(blank=True, null=True)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_containers', to='hosts.host')),
            ],
            options={
                'ordering': ['stack', 'name'],
                'indexes': [models.Index(fields=['host', 'stack'], name='hosts_docke_host_id_ca5299_idx')],
            },
        ),
    ]
