# Generated by Django 5.2.12 on 2026-07-14 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_dockercontainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnmanagedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('device_type', models.CharField(choices=[('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('printer', 'Printer'), ('nas', 'NAS'), ('server', 'Server'), ('workstation', 'Workstation'), ('camera', 'Camera'), ('ups', 'UPS'), ('iot', 'IoT Device'), ('other', 'Other')], default='other', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
