# Generated by Django 5.2.13 on 2026-08-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_unmanageddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='maintenance_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
