# Generated by Django 5.2.13 on 2026-08-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_host_maintenance_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostFirewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(blank=True, default='', max_length=32)),
                ('supported', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=None, null=True)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('profiles', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('unparsed', models.JSONField(blank=True, default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firewall', to='hosts.host')),
            ],
        ),
    ]
