# Generated by Django 5.2.17 on 2026-08-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_host_reboot_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('key', models.CharField(db_index=True, max_length=120, unique=True)),
                ('kind', models.CharField(choices=[('manual', 'Set by an operator'), ('auto', 'Derived from inventory'), ('agent', 'Advertised by the agent')], default='manual', max_length=8)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
