# Generated by Django 5.2.17 on 2026-08-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0012_populate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='tag_rows',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='hosts.tag'),
        ),
    ]
