# Generated by Django 5.2.17 on 2026-09-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0014_link_tag_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='docker_snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
