# Generated by Django 5.2.17 on 2026-09-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_host_docker_snapshot_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='windows_updates',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='windows_updates_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
