# Generated by Django 5.2.17 on 2026-09-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_transportack'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='machine_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
    ]
