# Generated by Django 5.2.17 on 2026-09-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("hosts", "0017_transportack")]
    operations = [
        migrations.AddField(
            model_name="host",
            name="agent_features",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
