# Generated by Django 5.2.17 on 2026-09-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0018_host_agent_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='agent_allow_reprovision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='agent_allowlist',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
