# Generated by Django 5.2.17 on 2026-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0019_host_agent_allowlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="container_engines",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
