# Generated by Django 5.2.17 on 2026-10-01 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0020_host_container_engines"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockercontainer",
            name="config_hash",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="dockercontainer",
            name="image_digest",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="dockercontainer",
            name="image_id",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="dockercontainer",
            name="restart_policy",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.CreateModel(
            name="ContainerStack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=200)),
                ("config_files", models.JSONField(blank=True, default=list)),
                ("working_dir", models.CharField(blank=True, max_length=500)),
                (
                    "ownership",
                    models.CharField(
                        choices=[
                            ("managed", "Managed by Vigil"),
                            ("adopted", "Adopted"),
                            ("external", "External"),
                        ],
                        default="external",
                        max_length=10,
                    ),
                ),
                ("engine", models.CharField(blank=True, max_length=10)),
                ("container_count", models.PositiveIntegerField(default=0)),
                ("running_count", models.PositiveIntegerField(default=0)),
                ("seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_stacks",
                        to="hosts.host",
                    ),
                ),
            ],
            options={
                "ordering": ("project",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "project"), name="uniq_container_stack"
                    )
                ],
            },
        ),
    ]
