# Generated by Django 5.2.17 on 2026-10-01 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0022_log_tail_session"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerImageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_name", models.CharField(max_length=200)),
                ("image_ref", models.CharField(blank=True, max_length=255)),
                ("image_id", models.CharField(max_length=80)),
                ("image_digest", models.CharField(blank=True, max_length=300)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_image_history",
                        to="hosts.host",
                    ),
                ),
            ],
            options={
                "ordering": ("-recorded_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["host", "container_name"],
                        name="hosts_conta_host_id_dbbb93_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContainerRollback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_name", models.CharField(max_length=200)),
                ("image", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_rollbacks",
                        to="hosts.host",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "container_name"),
                        name="uniq_container_rollback",
                    )
                ],
            },
        ),
    ]
