# Generated by Django 5.2.17 on 2026-10-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0018_host_machine_id'),
        ('hosts', '0023_container_rollback'),
    ]

    operations = [
    ]
