# Generated by Django 5.2.17 on 2026-10-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0024_merge_0018_host_machine_id_0023_container_rollback'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='agent_runs_as_root',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
