# Generated by Django 5.2.17 on 2026-10-08 18:39

import hashlib

from django.db import migrations

PREFIX = "sha256$"


def hash_tokens(apps, schema_editor):
    """Store every agent token as a SHA-256 (architect review, 2026-10-08).
    Agents keep presenting their plaintext token; the server hashes it to look
    the host up, so nothing changes for a running agent."""
    Host = apps.get_model("hosts", "Host")
    for host in Host.objects.exclude(agent_token__startswith=PREFIX).only("id", "agent_token"):
        host.agent_token = PREFIX + hashlib.sha256(host.agent_token.encode()).hexdigest()
        host.save(update_fields=["agent_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0025_host_agent_runs_as_root'),
    ]

    operations = [
        # One way: a hash cannot be turned back into the token.
        migrations.RunPython(hash_tokens, migrations.RunPython.noop),
    ]
