# Generated by Django 5.2.13 on 2026-07-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0002_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinestep',
            name='params_override',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
