# Generated by Django 5.2.13 on 2026-07-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0003_baselinestep_params_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
