# Generated by Django 5.2.17 on 2026-08-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0005_baseline_allow_high_risk'),
        ('hosts', '0013_host_tag_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='target_tag_rows',
            field=models.ManyToManyField(blank=True, related_name='baselines', to='hosts.tag'),
        ),
    ]
