# Generated by Django 5.2.17 on 2026-08-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baselines', '0006_baseline_target_tag_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseline',
            name='community_uid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
